# These are supported funding model platforms

github: # Katlego 
patreon: # KatHost
open_collective: # Artreeland
ko_fi: # Katlego
tidelift: # npm
community_bridge: # cloud-KatHost
liberapay: # KatHost
issuehunt: # KatHost
lfx_crowdfunding: # KatHost
polar: # Artrreland
buy_me_a_coffee: # Artreeland
thanks_dev: # KatHost
custom: # https://youtube.com/@nevagroweak?si=Xq3ajOuF7rALHlgz
